### PR TITLE
Update gulp to v. 4.0.2 (needed to upgrade to node 12.16 LTS)

### PR DESCRIPTION
**Pull request by Simon-Tesla**
Various package minver updates

### CODE REVIEW

**Comment by Simon-Tesla** [comment]
@Eupeptic1 I needed to make this change because I'm working on another project that requires Node 12, and gulp 3.9 doesn't like working with Node 12 at all for some reason. You may need to uninstall/reinstall your global gulp installation for gulp to work again, e.g.:
```
$ npm uninstall -g gulp
$ npm install -g gulp gulp-cli
```

You probably won't need to upgrade Node to take this change (I hope), but if that turns out to not be the case you should try to upgrade to the Node 12.16.1 LTS version if you can.

**Comment by Eupeptic1** [comment]
Thanks for the heads-up!  I haven't caught myself up to your master yet, so for the moment I can still build with my existing versions of gulp and Node.

I should be creating a pull request in the next day or two; I will probably catch up to your master before I do that.  If upgrading gulp (and maybe Node) turns into a mess, then I'll locally edit package.json to go back down to 3.9.1, so I can build, and then work on the upgrade later - unless there are other changes that require 4.0.2 to work, like, you changed the syntax in the makefile (or equal) to something that only >=4 understands.

Just for fun, this is what I have right now...

```shell

$ gulp --version
CLI version: 2.2.0
Local version: Unknown

$ nodejs --version
v4.9.1

```

(Yes, I get lots of "thingy 1.2 is deprecated, please upgrade to thingy 87.3 or better" warnings when I do one step of the build.  :D )

**Comment by Simon-Tesla** [comment]
Hmm, `node` is the executable for me on my system, so if that's correct on your system that's a *really* old version of node.

At v. 4, gulp split into the packages `gulp` and `gulp-cli`, the latter which provides the command-line interface. Version 2.2.0 is the current version of `gulp-cli`. Gulp changed their API in version 4 so you'd need to make some changes to the gulpfile to continue running at an older version.

After this release I'm going to be trying to get rid of as many of those warnings as I can. Upgrading gulp took care of a few at least.

**Comment by Eupeptic1** [comment]
Yesterday, I caught up to your master and then tried to build Raccoony with my existing versions of everything, which didn't work.  The hard failure was on `bufferutil`, which is currently at version 4.x or higher, but the highest version that would build under the Node I had was 3.x.  I tried to lock that one package at 3.x with `npm install --save bufferutil@3`, and _then_ build Raccoony, but that caused other badness in the build process and I couldn't complete the build.

I ended up completely uninstalling the Node I had, installing from the Node 12.x repo on nodesource.com , and then Raccoony built OK.  `node --version` now says `v12.16.1`.

I don't remember if I checked for a `node` executable on my Node 4.9.1 install.  With 12.x, the real executable is `/usr/bin/node`, and `/usr/bin/nodejs` is just a symlink (via the Debian alternatives system) to `/usr/bin/node`.

**Pull request merged**
